server:
    port: 8080
    context-path: /user-crud-service/webapi

spring: 
    main:
        banner-mode: "off"     

logging: 
    level: 
        org.springframework: INFO
        com.uwefuchs.demo.heroestutorial.service: DEBUG
